### ISSUE TITLE
Bad method call

### ISSUE THREAD

**Issue by isaacdarcilla** [LoveDuckie/silverstripe-json-ld-structured-data#1]
Using latest silverstripe framework

**Comment by LoveDuckie** [comment]
I'll take a look into it.

**Comment by LoveDuckie** [comment]
I've removed all invocations of `SiteConfig::current_site_config()->getWebsiteTitle()`, as that is an extension method that is being defined elsewhere in my personal project, but verify for yourself if that remains to be the case.

If it's still breaking, then please include a screenshot of the full stacktrace so that I can locate the offending code.

Thanks for reporting the issue!
